# Generated by Django 2.2.2 on 2019-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntopic', models.CharField(max_length=100)),
                ('ndetail', models.CharField(max_length=1000)),
                ('ndate', models.CharField(max_length=20)),
            ],
        ),
    ]
